7.2
rprtr258/spbsu-homework pull request #3
Opened 2017-11-12 16:28 UTC by rprtr258

added task 7.2 and changed bst for avl tree

2017-11-25 09:15 UTC, jzuken commented
тут та же проблема с удалением корня

2017-11-25 09:16 UTC, jzuken requested changes

2017-11-25 09:16 UTC, jzuken commented on semester1/hw7/7.1/main.cpp
> +#include <stdio.h>
7.1 тут что делает? в этой ветке и пуллреквесте должен быть код только одной задачи

2017-12-15 11:12 UTC, jzuken requested changes

2017-12-15 11:12 UTC, jzuken commented on semester1/hw7/7.1/main.cpp
> -#include <stdio.h>
и что будет, если я это смерджу в мастер? правильно, задача 7.1 оттуда удалится.
сделай новую ветку

2017-12-15 11:12 UTC, jzuken commented on semester1/hw6/6.2/main.cpp
> +}
все следующие коммиты с подобными комментариями я буду заставлять откатывать

2017-12-15 11:59 UTC, rprtr258 commented on semester1/hw7/7.1/main.cpp
> -#include <stdio.h>
7.1 не удалится потому что ее нет в мастере

2017-12-15 19:26 UTC, rprtr258 commented on semester1/hw7/7.1/main.cpp
> -#include <stdio.h>
я же удалял это только в этой ветке чтобы не было файлов другой задачи, вроде при мердже все нормально должно быть

2017-12-16 14:00 UTC, jzuken commented on semester1/hw7/7.1/main.cpp
> -#include <stdio.h>
ну рано или поздно то она там появится, и этот коммит наложится сверху и удалить её нафиг

2017-12-16 14:04 UTC, rprtr258 commented on semester1/hw7/7.1/main.cpp
> -#include <stdio.h>
я не понимаю как этот пуллреквест что-то удалит, он же хранит только изменения от мастера и в них нет никакого удаления файлов других реквестов. То что я удалил 7.1 в одном из коммитов в этом пулл реквесте абсолютно никак не должно влиять на действительную папку с 7.1 в мастере, ибо в в изменении этого реквеста(7.2) ничего про него не сказано, а удалена была лишь папка которая не связана с папкой из 7.1 или я не прав где-то?

2017-12-16 14:05 UTC, rprtr258 commented on semester1/hw7/7.1/main.cpp
> -#include <stdio.h>
все же изменения в реквесте отображаются в "Files changed" и там нет никакого 7.1

2017-12-16 14:28 UTC, rprtr258 commented on semester1/hw7/7.1/main.cpp
> -#include <stdio.h>
если кто и удалит 7.1 из мастера так это только сам пулл реквест 7.1

2017-12-16 14:32 UTC, rprtr258 commented on semester1/hw7/7.1/main.cpp
> -#include <stdio.h>
вот сейчас я удалил неправильную задачу 7.1 из мастера, теперь вопросов вроде быть не должно

2017-12-24 07:34 UTC, merged