4.1
rprtr258/spbsu-homework pull request #46
Opened 2018-03-06 20:01 UTC by rprtr258

2018-03-13 14:03 UTC, jzuken requested changes

2018-03-13 14:03 UTC, jzuken commented on semester2/hw4/4.1/src/main/java/com/rprtr258/util/EmptyListException.java
> +public class EmptyListException extends RuntimeException {
опять непроверяемое исключение :(

2018-03-13 14:03 UTC, jzuken commented on semester2/hw4/4.1/src/main/java/com/rprtr258/util/SinglyLinkedList.java
> +        head = null;
а тут ещё раз? на случай, если первые два не сработали? :)

2018-03-13 14:07 UTC, rprtr258 commented on semester2/hw4/4.1/src/main/java/com/rprtr258/util/SinglyLinkedList.java
> +        head = null;
что еще раз?

2018-03-13 20:21 UTC, rprtr258 commented on semester2/hw4/4.1/src/main/java/com/rprtr258/util/EmptyListException.java
> +public class EmptyListException extends RuntimeException {
Если я сделаю его проверяемым мне придется прописывать его в методе append UniqueList, а так как он наследуется от SinglyLinkedList, то и в его методе append тоже надо прописывать это исключение, хотя его там не может быть.

2018-03-13 20:26 UTC, rprtr258 commented on semester2/hw4/4.1/src/main/java/com/rprtr258/util/EmptyListException.java
> +public class EmptyListException extends RuntimeException {
Даже если это как-то и решается, то т.к. UniqueList не отличим от SinglyLinkedList, то есть им можно пользоваться как SinglyLinkedList, но тогда append может бросать проверяемое исключение, которое не может бросать чистый SinglyLinkedList.

2018-03-14 04:17 UTC, jzuken commented on semester2/hw4/4.1/src/main/java/com/rprtr258/util/EmptyListException.java
> +public class EmptyListException extends RuntimeException {
Да, это проблемка. Я на паре поговорю в следующий раз, как с этим можно бороться, пусть пока так останется

2018-04-23 09:48 UTC, merged